version: '3'

services:

  web2:
    build:
      context:
        ./web_core
    container_name: dev-web-2
    volumes:
      - ./web_core:/app
      - /home/ubuntu/web_core/dev/web_core/media:/app/media
    ports:
      - "8001:8000"
  nginx2:
    image: nginx:latest
    container_name: nginx3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/web_core/dev/web_core/media:/app/media
    ports:
      - "81:80"
    depends_on:
      - web2
