# Generated by Django 5.0.6 on 2024-07-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('widget_id', models.IntegerField()),
                ('content_id', models.IntegerField()),
                ('language_key', models.CharField(max_length=64)),
                ('content_group', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=128)),
                ('order', models.IntegerField()),
                ('language_key', models.CharField(max_length=64)),
                ('navigation_id', models.IntegerField(blank=True, default=None, null=True)),
                ('navigation_type', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=128)),
                ('order', models.IntegerField()),
                ('language_key', models.CharField(max_length=64)),
                ('navigation_id', models.IntegerField(blank=True, default=None, null=True)),
                ('navigation_type', models.CharField(max_length=255)),
                ('change_type', models.CharField(max_length=128)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=512)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=128)),
                ('place', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('graduate', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=128)),
                ('qualification_category', models.CharField(max_length=128)),
                ('place_of_work', models.TextField()),
                ('job', models.CharField(max_length=128)),
                ('teaching_experience', models.IntegerField()),
                ('experience_by_position', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WidgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.IntegerField()),
                ('widget_type', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('language_key', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('navigation_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('widget_type', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('language_key', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('navigation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='web_api.navigation')),
            ],
        ),
    ]
