# Generated by Django 5.0.6 on 2024-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_api', '0002_alter_navigationhistory_id_alter_widgethistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newscontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='othercontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='widget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
