# Generated by Django 5.0.6 on 2024-06-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_api', '0004_alter_widget_navigation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgethistory',
            name='navigation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof_api.navigationhistory'),
        ),
    ]
