# Generated by Django 5.0.6 on 2024-06-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_api', '0005_alter_widgethistory_navigation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercontent',
            name='content',
            field=models.JSONField(),
        ),
    ]
