# Generated by Django 5.0.6 on 2024-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_api', '0006_alter_othercontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgethistory',
            name='navigation_id',
            field=models.IntegerField(),
        ),
    ]
